### ISSUE TITLE
http 404 error during boot

### ISSUE THREAD

**Issue by tompre** [biemster/rpi4_alpine_netboot#3]
I'm unable to boot the pi with the current configuration.
I get the following error in the http server log.
`"GET /alpine/v3.12/main/overlay.tar.gz HTTP/1.1" 404 -`

The path on the sever is '/overlay.tar.gz' and I can access it using a browser.

**Comment by biemster** [comment]
I probably need a bit more info, but if I understand correctly that the full path is \<http root\>/overlay.tar.gz then this is not correct. It should be \<http root\>/alpine/v3.12/main/overlay.tar.gz (as your server log indicates).

(sorry for the edits, that was confusing)

**Comment by tompre** [comment]
Thx for your reply, sorry for being so unclear.

I can see in the script that the path to the files is set in the cmdline.txt file and I was expecting that
the script would create a similar structure in the "http" folder.
What I end up with however is only  "python_httpserver.sh", "aarch64", and the overlay.

How is the http server supposed to know that "alpine/v3.12/main/" is supposed to point to the root http folder.

I was able to fix it manually by adding a symlink form "alpine/v3.12/main" to "http".

**Comment by biemster** [comment]
Nice to see you were able to fix your problem, and you are correct, thanks for catching this. On my own setup I actually only test with a full httpserver which serves the `http` folder, I'm not using the python script. So this slipped through the cracks. I'll fix it in the next commit, and then close this issue.

Is the whole workflow now working for you?

**Comment by tompre** [comment]
It works perfectly now! Thanks you!
